// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package transcription

import (
	"doubao-speech-service/api/transcription"
)

type ControllerV1 struct{}

func NewV1() transcription.ITranscriptionV1 {
	return &ControllerV1{}
}
