// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"doubao-speech-service/internal/dao/internal"
)

// transcriptionDao is the data access object for the table transcription.
// You can define custom methods on it to extend its functionality as needed.
type transcriptionDao struct {
	*internal.TranscriptionDao
}

var (
	// Transcription is a globally accessible object for table transcription operations.
	Transcription = transcriptionDao{internal.NewTranscriptionDao()}
)

// Add your custom methods and functionality below.
